on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: LOWPROKB/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2
    with:
      build_matrix_path: config/build.yml
      config_path: config
